version: "3.5"

services:
  postgres:
    image: postgres:15.4
    volumes:
      - blogs:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init-database.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: blogs
    ports:
      - "5432:5432"
    networks:
      - blogs-api
    restart: unless-stopped

  backend:
    build:
      context: blogs-api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 9090:9090
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blogs
      X_API_KEY_THE_BASICS: ""
    networks:
      - blogs-api

networks:
  blogs-api:
    driver: bridge

volumes:
  blogs:
    driver: local
