version: "3.5"

services:
  postgres:
    image: postgres:15.4
    volumes:
      - blogs:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init-database.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: blogs
    ports:
      - "5432:5432"
    networks:
      - blogs-api
    restart: unless-stopped

networks:
  blogs-api:
    driver: bridge

volumes:
  blogs:
    driver: local
